# [Info]
site_name: Carrot World # 左上角标题
site_url: https://github.com/root-hbx # 可以修改！
site_author: Boxuan Hu
site_description: 胡博瑄的学习主页

# [Navigtion]
nav:
  - 基础运维知识:
    - LECTURE/index.md 
    - Linux:
      - Linux讲座: LECTURE/Linux/linux.md
      - Linux101教程: LECTURE/Linux/linux101.md
      - 命令行入门精简版: LECTURE/Linux/commands-concise.md
    - Shell:
      - Linux命令行的艺术: LECTURE/Shell/Linux命令行的艺术.md
      - MacOS命令行的艺术: LECTURE/Shell/MacOS命令行的艺术.md
      - Shell脚本编程: LECTURE/Shell/Shell脚本编程.md
    - Markdown:
      - Markdown讲座: LECTURE/Markdown/markdown.md
      - Markdown教程: LECTURE/Markdown/markdown_Tutorial.md
      - VSCode及插件安装: LECTURE/Markdown/vscode-extension.md
    - Git:
      - Git学习指南: LECTURE/Git/git学习指南前言.md
      - Git个人使用: LECTURE/Git/git个人使用.md
      - Git团队协作: LECTURE/Git/git团队协作.md
      - Gitignore使用规范: LECTURE/Git/gitignore使用规范.md
      - Windows安装Git: LECTURE/Git/windows-install.md
    - Docker:
      - Docker学习指南前言: LECTURE/Docker/Docker学习指南前言.md
      - Docker安装: LECTURE/Docker/Docker安装.md
      - Docker制作镜像: LECTURE/Docker/Docker制作镜像.md
      - Docker目录挂载: LECTURE/Docker/Docker目录挂载.md
      - Docker多容器通信: LECTURE/Docker/Docker多容器通信.md
      - Docker多服务集成运行: LECTURE/Docker/Docker多服务集成运行.md
      - Docker发布与部署: LECTURE/Docker/Docker发布与部署.md
    - ns-3:
      - 保姆级配置教程: LECTURE/ns-3/ns3.md
    - OhMyZsh:
      - mac的终端优化: LECTURE/terminal_zsh/oh_my_zsh.md
    
  - 常用开发简介:
    - BLOG/index.md
    - BLOG/others.md
    - BLOG/tool.md
    - Markdown:
      - 基础语法介绍: BLOG/Markdown/grammars.md
    - GithubPages:
      - Mkdocs with GithubPages: BLOG/Markdown/mkdocs-site.md
      - MdBook with GithubPages: BLOG/Markdown/mdbook-site.md
      - GithubPages: BLOG/Markdown/github-pages.md
    - Linux:
      - BLOG/Linux/tmux.md
      - BLOG/Linux/unix.md
      - BLOG/Linux/kernel-compile.md
      - BLOG/Linux/pi-start.md
    - OS:
      - BLOG/OS/fork-exec-spawn.md
      - BLOG/OS/fork-example.md
    - Vim:
      - Vim 配置指南: BLOG/Vim/Vim配置指南.md
      - Vim 学习笔记: BLOG/Vim/vim.md
    - 在macOS上用VSCode写C++代码:
      - 0 介绍: BLOG/vscode-cpp/0_about.md
      - 1 前言和课程说明: BLOG/vscode-cpp/1_前言和课程说明.md
      - 2 认识macOS的文件系统: BLOG/vscode-cpp/2_认识macOS的文件系统.md
      - 3 认识程序: BLOG/vscode-cpp/3_认识程序.md
      - 4 认识终端和shell: BLOG/vscode-cpp/4_认识终端和shell.md
      - 5 开启VSCode的大门: BLOG/vscode-cpp/5_开启VSCode的大门.md
      - 6 VSCode代码运行自动化: BLOG/vscode-cpp/6_VSCode代码运行自动化.md
      - 7 用VSCode调试Cpp代码: BLOG/vscode-cpp/7_用VSCode调试Cpp代码.md
      - 8 课程回顾: BLOG/vscode-cpp/8_课程回顾.md
      - 9 其他: BLOG/vscode-cpp/9_others.md
      - 10 极速入门版: BLOG/vscode-cpp/10_极速版.md
      - 11 补充: BLOG/vscode-cpp/11_补充.md

  - 计算机课程整理:
    - curriculum_study/index.md
    - C++ Primer Plus:
      - Chapter 2 开始学习C++: curriculum_study/C++PrimerPlus/chapter2开始学习c++.md
      - Chapter 3 处理数据: curriculum_study/C++PrimerPlus/chapter3处理数据.md
      - Chapter 4 复合类型: curriculum_study/C++PrimerPlus/chapter4复合类型.md
      - Chapter 5 循环与关系表达式: curriculum_study/C++PrimerPlus/chapter5循环与关系表达式.md
      - Chapter 6 分支语句与逻辑运算符: curriculum_study/C++PrimerPlus/chapter6分支语句与逻辑运算符.md
      - Chapter 7 函数 - C++的编程模块: curriculum_study/C++PrimerPlus/chapter7函数-c++的编程模块.md
      - Chapter 8 函数探幽(上): curriculum_study/C++PrimerPlus/chapter8函数探幽(上).md
      - Chapter 8 函数探幽(下): curriculum_study/C++PrimerPlus/chapter8函数探幽(下).md
      - Chapter 9 内存模型和名称空间: curriculum_study/C++PrimerPlus/chapter9内存模型和名称空间.md
      - Chapter 10 对象和类: curriculum_study/C++PrimerPlus/chapter10对象和类.md
      - Chapter 11 使用类: curriculum_study/C++PrimerPlus/chapter11使用类.md
      - Chapter 12 类和动态内存分配: curriculum_study/C++PrimerPlus/chapter12类和动态内存分配.md
      - Chapter 13 类继承: curriculum_study/C++PrimerPlus/chapter13类继承.md
      - Chapter 14 C++中的代码重用: curriculum_study/C++PrimerPlus/chapter14c++中的代码重用.md
      - Chapter 15 友元、异常和其他: curriculum_study/C++PrimerPlus/chapter15友元、异常和其他.md
      - Chapter 16 String类和标准模板库: curriculum_study/C++PrimerPlus/chapter16string类和标准模板库.md
      - Chapter 17 输入、输出和文件: curriculum_study/C++PrimerPlus/chapter17输入、输出和文件.md
      - Chapter 18 探讨C++新标准: curriculum_study/C++PrimerPlus/chapter18探讨c++新标准.md
    - Computer Systems - A Programmer's Perspective:
      - Chapter 0 常见汇编指令: curriculum_study/CSAPP_CMU/常见汇编指令.md
      - Chapter 2 信息的表示和处理: curriculum_study/CSAPP_CMU/chapter2_信息的表示和处理.md
      - Chapter 3 程序的机器级表示: curriculum_study/CSAPP_CMU/chapter3_程序的机器级表示.md
      - Chapter 5 优化程序性能: curriculum_study/CSAPP_CMU/chapter5_优化程序性能.md
      - Chapter 6 存储器的层次结构: curriculum_study/CSAPP_CMU/chapter6_存储器的层次结构.md
      - Chapter 7 链接: curriculum_study/CSAPP_CMU/chapter7_链接.md
    - Computer Networking - A Top-Down Approach:
      - Chapter 1 计算机网络概述: curriculum_study/TD_net/ch1.md
      - Chapter 2 应用层: curriculum_study/TD_net/ch2.md
      - Chapter 3 传输层: curriculum_study/TD_net/ch3.md
      - Chapter 4 网络层 - 数据平面: curriculum_study/TD_net/ch4.md
      - Chapter 5 网络层 - 控制平面: curriculum_study/TD_net/ch5.md      
      - Chapter 6 链路层: curriculum_study/TD_net/ch6.md
    - Info Theory:
      - Lecture 3 AEP: curriculum_study/Info-theory/lec3.md
      - Lecture 4 Entropy Rate: curriculum_study/Info-theory/lec4.md
      - Lecture 5 Data Compression Part1: curriculum_study/Info-theory/lec5.md
      - Lecture 6 Data Compression Part2: curriculum_study/Info-theory/lec6.md
      - Lecture 7 Data Compression Part3: curriculum_study/Info-theory/lec7.md
      - Lecture 8 Channel Capacity Part1: curriculum_study/Info-theory/lec8.md
      - Lecture 9 Channel Capacity Part2: curriculum_study/Info-theory/lec9.md
      - Lecture 10 Channel Capacity Part3: curriculum_study/Info-theory/lec10.md
      - Lecture 11 Differential Entropy Part1: curriculum_study/Info-theory/lec11.md
      - Lecture 12 Differential Entropy Part2: curriculum_study/Info-theory/lec12.md
      - Lecture 13 Gaussian Channel: curriculum_study/Info-theory/lec13.md
      - Lecture 14 Review: curriculum_study/Info-theory/lec14.md
    - Algorithm Design:
      - Part 1 期末备考指南: curriculum_study/Algorithm_XJTU/qimo_review.md
      - Part 2 常用算法模板: curriculum_study/Algorithm_XJTU/qimo_big.md
      - Part 3 练习题: curriculum_study/Algorithm_XJTU/qimo_exe.md
    - Software Defined Network:
      - Lecture 0 Preface: curriculum_study/SDN/Lecture0_Preface.md
      - Lecture 1 Network Fundamentals: curriculum_study/SDN/Lecture1_Network_Fundamentals.md
    - Introduction to 2D Game Development:
      - Outline: curriculum_study/Introduction_to_2D_Game_Development/M0.md
      - Module 1 Game Engine + Objects: curriculum_study/Introduction_to_2D_Game_Development/M1.md
      - Module 2 Bounds + Navigation: curriculum_study/Introduction_to_2D_Game_Development/M2.md
      - Module 3 UI, Interaction, Game Manager, Gradual Changes, Autonomous Behavior: curriculum_study/Introduction_to_2D_Game_Development/M3.md
      - Module 4 Camera manipulations, and multiple views: curriculum_study/Introduction_to_2D_Game_Development/M4.md

  - 优秀论文整理:
    - sci/index.md
    - 计算机网络:
      - SIGCOMM16 RDMA over Commodity Ethernet at Scale:
        - Abstruct: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/RDMA_over_Commodity_Ethernet_at_Scale(Abstruct).md
        - Background: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/RDMA_over_Commodity_Ethernet_at_Scale(Background).md
        - Introduction: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/RDMA_over_Commodity_Ethernet_at_Scale(Introduction).md
        - Conclusion: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/RDMA_over_Commodity_Ethernet_at_Scale(Conclusion).md
        - DSCP-BASED PFC: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/3_DSCP-BASED PFC.md
        - RDMA Transport Livelock: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/4.1_RDMA_transport_livelock(传输活锁).md
        - PFC Deadlock: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/4.2_PFC Deadlock.md
        - NIC/PFC Pause Frame Storm: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/4.3_NIC_PFC_pause_frame_storm.md
        - Slow Receiver Symptom: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/4.4_The_Slow-receiver_symptom.md
        - RDMA in Production: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/5_RDMA_In_Production.md
        - Experiences: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/6_EXPERIENCES.md
        - Related Work: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/7_RELATED WORK.md
        - Conclusion: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/8_CONCLUSION.md
        - Review: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/“读后感”.md
        - Some Ideas: sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/issue_thinking.md
      - ICDCS23 Less is More Dynamic and Shared Headroom Allocation in PFC-enabled Datacenter Networks:
        - Abstruct: sci/计算机网络/LessIsMore/LessIsMore_Abstruct.md
        - Introduction: sci/计算机网络/LessIsMore/LessIsMore_Introduction.md
        - Background: sci/计算机网络/LessIsMore/LessIsMore_Background.md
        - Motivation: sci/计算机网络/LessIsMore/LessIsMore_Motivation.md
        - DSH Design: sci/计算机网络/LessIsMore/LessIsMore_DSH_Design.md
        - Evaluation: sci/计算机网络/LessIsMore/LessIsMore_Evaluation.md
        - Related Work: sci/计算机网络/LessIsMore/LessIsMore_RelatedWork.md
        - Conclusion: sci/计算机网络/LessIsMore/LessIsMore_Conclusion.md
        - Review: sci/计算机网络/LessIsMore/整理与思考.md
  
  - 科研软件指南:
    - Sci_doc/index.md
    - ns-3:
      - 0 ns-3 基础配置: Sci_doc/ns-3/ch0.md
      - 1 ns-3入门程序解析: Sci_doc/ns-3/ch1.md
      - 2 ns-3 参数控制: Sci_doc/ns-3/ch2.md
      - 3 ns-3 模拟建立拓扑: Sci_doc/ns-3/ch3.md
      - 4 ns-3 Tracing的全部实现机理: Sci_doc/ns-3/ch4.md
      - 5 ns-3 Data Collection: Sci_doc/ns-3/ch5.md
      - 6 ns-3 复盘思考: Sci_doc/ns-3/ch6.md

  - 自我介绍:
    - ME/index.md
    - 个人特点: ME/description.md
    - 个人能力: ME/ability.md
    - 个人经历: ME/experience.md
    - 有意义的照片: ME/php.md
  
  - 《胡说》:
    - HuSay/index.md
    - HuSay/20231123.md


# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: pink # 上方的颜色
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: pink
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/root-hbx # 右上角点击跳转的链接
repo_name: root-hbx # 右上角的名字
## [bottom-left corner]
copyright: Boxuan Hu  CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols