# [Info]
site_name: carrot_world # 左上角标题
site_url: https://github.com/root-hbx # 可以修改！
site_author: 胡博瑄
site_description: 胡博瑄的学习网站

# [Navigtion]
nav:
  - 基础运维知识:
    - LECTURE/index.md 
    - Linux:
      - Linux讲座: LECTURE/Linux/linux.md
      - Linux101教程: LECTURE/Linux/linux101.md
      - 命令行入门精简版: LECTURE/Linux/commands-concise.md
    - Shell:
      - Linux命令行的艺术: LECTURE/Shell/Linux命令行的艺术.md
      - MacOS命令行的艺术: LECTURE/Shell/MacOS命令行的艺术.md
      - Shell脚本编程: LECTURE/Shell/Shell脚本编程.md
    - Markdown:
      - Markdown讲座: LECTURE/Markdown/markdown.md
      - Markdown教程: LECTURE/Markdown/markdown_Tutorial.md
      - VSCode及插件安装: LECTURE/Markdown/vscode-extension.md
    - Git:
      - Git学习指南: LECTURE/Git/git学习指南前言.md
      - Git个人使用: LECTURE/Git/git个人使用.md
      - Git团队协作: LECTURE/Git/git团队协作.md
      - Gitignore使用规范: LECTURE/Git/gitignore使用规范.md
      - Windows安装Git: LECTURE/Git/windows-install.md
    - Docker:
      - Docker学习指南前言: LECTURE/Docker/Docker学习指南前言.md
      - Docker安装: LECTURE/Docker/Docker安装.md
      - Docker制作镜像: LECTURE/Docker/Docker制作镜像.md
      - Docker目录挂载: LECTURE/Docker/Docker目录挂载.md
      - Docker多容器通信: LECTURE/Docker/Docker多容器通信.md
      - Docker多服务集成运行: LECTURE/Docker/Docker多服务集成运行.md
      - Docker发布与部署: LECTURE/Docker/Docker发布与部署.md
    - ns-3:
      - 保姆级配置教程: LECTURE/ns-3/ns3.md
    - terminal_zsh:
      - mac的终端优化: LECTURE/terminal_zsh/oh_my_zsh.md
    
  - 常用开发简介:
    - BLOG/index.md
    - BLOG/others.md
    - Markdown:
      - BLOG/Markdown/grammars.md
    - GithubPages:
      - BLOG/Markdown/mkdocs-site.md
      - BLOG/Markdown/mdbook-site.md
      - BLOG/Markdown/github-pages.md
    - Linux:
      - BLOG/Linux/tmux.md
      - BLOG/Linux/unix.md
      - BLOG/Linux/kernel-compile.md
      - BLOG/Linux/pi-start.md
    - OS:
      - BLOG/OS/fork-exec-spawn.md
      - BLOG/OS/fork-example.md
    - Vim:
      - BLOG/Vim/Vim配置指南.md
      - BLOG/Vim/vim.md
    - 在macOS上用VSCode写C++代码:
      - 0 介绍: BLOG/vscode-cpp/0_about.md
      - 1 前言和课程说明: BLOG/vscode-cpp/1_前言和课程说明.md
      - 2 认识macOS的文件系统: BLOG/vscode-cpp/2_认识macOS的文件系统.md
      - 3 认识程序: BLOG/vscode-cpp/3_认识程序.md
      - 4 认识终端和shell: BLOG/vscode-cpp/4_认识终端和shell.md
      - 5 开启VSCode的大门: BLOG/vscode-cpp/5_开启VSCode的大门.md
      - 6 VSCode代码运行自动化: BLOG/vscode-cpp/6_VSCode代码运行自动化.md
      - 7 用VSCode调试Cpp代码: BLOG/vscode-cpp/7_用VSCode调试Cpp代码.md
      - 8 课程回顾: BLOG/vscode-cpp/8_课程回顾.md
      - 其他: BLOG/vscode-cpp/9_others.md
      - 极速版: BLOG/vscode-cpp/10_极速版.md
      - 补充: BLOG/vscode-cpp/11_补充.md

  - 计算机课程整理:
    - curriculum_study/index.md
    - C++PrimerPlus:
      - curriculum_study/C++PrimerPlus/chapter2开始学习c++.md
      - curriculum_study/C++PrimerPlus/chapter3处理数据.md
      - curriculum_study/C++PrimerPlus/chapter4复合类型.md
      - curriculum_study/C++PrimerPlus/chapter5循环与关系表达式.md
      - curriculum_study/C++PrimerPlus/chapter6分支语句与逻辑运算符.md
      - curriculum_study/C++PrimerPlus/chapter7函数-c++的编程模块.md
      - curriculum_study/C++PrimerPlus/chapter8函数探幽(上).md
      - curriculum_study/C++PrimerPlus/chapter8函数探幽(下).md
      - curriculum_study/C++PrimerPlus/chapter9内存模型和名称空间.md
      - curriculum_study/C++PrimerPlus/chapter10对象和类.md
      - curriculum_study/C++PrimerPlus/chapter11使用类.md
      - curriculum_study/C++PrimerPlus/chapter12类和动态内存分配.md
      - curriculum_study/C++PrimerPlus/chapter13类继承.md
      - curriculum_study/C++PrimerPlus/chapter14c++中的代码重用.md
      - curriculum_study/C++PrimerPlus/chapter15友元、异常和其他.md
      - curriculum_study/C++PrimerPlus/chapter16string类和标准模板库.md
      - curriculum_study/C++PrimerPlus/chapter17输入、输出和文件.md
      - curriculum_study/C++PrimerPlus/chapter18探讨c++新标准.md
    - CSAPP_(CMU):
      - curriculum_study/CSAPP_CMU/常见汇编指令.md
      - curriculum_study/CSAPP_CMU/chapter2_信息的表示和处理.md
      - curriculum_study/CSAPP_CMU/chapter3_程序的机器级表示.md
      - curriculum_study/CSAPP_CMU/chapter5_优化程序性能.md
      - curriculum_study/CSAPP_CMU/chapter6_存储器的层次结构.md
      - curriculum_study/CSAPP_CMU/chapter7_链接.md
    - TD_net:
      - curriculum_study/TD_net/ch1.md
      - curriculum_study/TD_net/ch2.md
      - curriculum_study/TD_net/ch3.md
      - curriculum_study/TD_net/ch4.md
      - curriculum_study/TD_net/ch5.md      
      - curriculum_study/TD_net/ch6.md
    - Info-theory:
      - curriculum_study/Info-theory/lec3.md
      - curriculum_study/Info-theory/lec4.md
      - curriculum_study/Info-theory/lec5.md
      - curriculum_study/Info-theory/lec6.md
      - curriculum_study/Info-theory/lec7.md
      - curriculum_study/Info-theory/lec8.md
      - curriculum_study/Info-theory/lec9.md
      - curriculum_study/Info-theory/lec10.md
      - curriculum_study/Info-theory/lec11.md
      - curriculum_study/Info-theory/lec12.md
      - curriculum_study/Info-theory/lec13.md
      - curriculum_study/Info-theory/lec14.md
    - Algorithm_design:
      - curriculum_study/Algorithm_XJTU/qimo_review.md
      - curriculum_study/Algorithm_XJTU/qimo_big.md
      - curriculum_study/Algorithm_XJTU/qimo_exe.md

  - 优秀论文整理:
    - sci/index.md
    - 计算机网络:
      - RDMA_over_Commodity_Ethernet_at_Scale:
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/RDMA_over_Commodity_Ethernet_at_Scale(Abstruct).md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/RDMA_over_Commodity_Ethernet_at_Scale(Background).md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/RDMA_over_Commodity_Ethernet_at_Scale(Introduction).md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/RDMA_over_Commodity_Ethernet_at_Scale(Conclusion).md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/3_DSCP-BASED PFC.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/4.1_RDMA_transport_livelock(传输活锁).md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/4.2_PFC Deadlock.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/4.3_NIC_PFC_pause_frame_storm.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/4.4_The_Slow-receiver_symptom.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/5_RDMA_In_Production.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/6_EXPERIENCES.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/7_RELATED WORK.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/8_CONCLUSION.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/“读后感”.md
        - sci/计算机网络/RDMA_over_Commodity_Ethernet_at_Scale/issue_thinking.md
      - ICDCS23_Less_is_More_Dynamic_and_Shared_Headroom_Allocation_in_PFC-enabled_Datacenter_Networks:
        - sci/计算机网络/LessIsMore/LessIsMore_Abstruct.md
        - sci/计算机网络/LessIsMore/LessIsMore_Introduction.md
        - sci/计算机网络/LessIsMore/LessIsMore_Background.md
        - sci/计算机网络/LessIsMore/LessIsMore_Motivation.md
        - sci/计算机网络/LessIsMore/LessIsMore_DSH_Design.md
        - sci/计算机网络/LessIsMore/LessIsMore_Evaluation.md
        - sci/计算机网络/LessIsMore/LessIsMore_RelatedWork.md
        - sci/计算机网络/LessIsMore/LessIsMore_Conclusion.md
        - sci/计算机网络/LessIsMore/整理与思考.md
  
  - 科研软件指南:
    - Sci_doc/index.md
    - ns-3:
      - 0 ns-3及其基础配置: Sci_doc/ns-3/ch0.md
      - 1 入门程序解析: Sci_doc/ns-3/ch1.md
      - 2 显示结果的优化: Sci_doc/ns-3/ch2.md
      - 3 模拟建立拓扑结构: Sci_doc/ns-3/ch3.md
      - 4 ns-3_tracing的全部实现机理: Sci_doc/ns-3/ch4.md
      - 5 ns-3_Data-Collection: Sci_doc/ns-3/ch5.md

  - hbx是谁:
    - ME/index.md
    - ME/description.md
    - ME/ability.md
    - ME/experience.md
    - ME/php.md
  
  - 《胡说》:
    - HuSay/20231123.md


# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/root-hbx # 右上角点击跳转的链接
repo_name: GithubRepo_of_hbx # 右上角的名字
## [bottom-left corner]
copyright: 胡博瑄 # 左下角的版权声明
## [bottom-right corner]

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols